version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8876:80
    container_name: nginx_project
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: app_project
    depends_on:
      - postgres
  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5431:5432
    container_name: db_project
    restart: always
    environment:
      POSTGRES_DB: 'quiz'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data