version: '3'

services:
  php:
    container_name: app_project
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

  nginx:
    image: nginx:1.23.2-alpine
    ports:
      - 8876:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
    container_name: nginx_project
    depends_on:
      - php
  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5431:5432
    container_name: db_project
    restart: always
    environment:
      POSTGRES_DB: 'quiz'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data